void updateWave() {
  int spacing = 1;
  if (balloons.size() == 0) {
    wave++;
    if (wave == 1) {
      balloons.add(p.getStart()[0], p.getStart()[1], 1.5, 1); 
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
    }
    if (wave == 2) {
      balloons.add(p.getStart()[0], p.getStart()[1], 1.5, 1); 
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
    }
    if (wave == 3) {
      balloons.add(p.getStart()[0], p.getStart()[1], 1.5, 1); 
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 1);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 2);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 2);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 2);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 2);
      spacing++;
      balloons.add(p.getStart()[0] - (p.getPoint(1)[0] - p.getPoint(0)[0]) / 5 * spacing, p.getStart()[1] - (p.getPoint(1)[1] - p.getPoint(0)[1]) / 5 * spacing, 1.5, 2);
    }
  }
}
